import os
DIRECTORY = os.getcwd()

KI_ID = "ckgudcjf"
KI_URL_PRACTICE = 'https://openapi.koreainvestment.com:9443'
KI_ACCOUNT_PRACTICE = '46640657-01'
KI_ACCOUNT_PRACTICE_C = '46640657'
KI_APPKEY_PRACTICE = 'PSVEqsBd9yTK2Gc3sJVJIjedOQOrFYvdNoX6'
KI_APPSECRET_PRACTICE = 'RW8o0UP1psLyvolcfbA9JV/Ss1Gg9UgLnfkttKaFZOawSwZT6XsxgsGO/GC8y0l9rJ8C4XVhwelyZfl2nol7EMqCCEMohI0WjPUimVwFuiHbLP0/oYDfmNFyQVs+hKBxolC5a4OyKzd/To1mTEEDPDl9zZl2Nsrc+36Cxv5Qe+W9NUpdet8='

KI_URL_IMITATION = 'https://openapivts.koreainvestment.com:29443'
KI_ACCOUNT_IMITATION = '50081061-01'
KI_ACCOUNT_IMITATION_C = '50081061'
KI_APPKEY_IMITATION = 'PSgFaLpCMY9CLFFUCaguWyDVdnOwnfYNQSPs'
KI_APPSECRET_IMITATION = 'FfxV9JO+iOSy+OiwyPl3Yh+UM7koPNcv0z6X6omA7w+0CCz7WSUtcMU+zz9ZL7P73YOGq8sVyr6UgII+R8lfczwTVcXeb0WQQUEB7/D1rz9TrH13vVjCVA8ciTBGi+QDj+bV4r5HJBJBZpgzRbCALs6D3XsC+4QXuwkT/leKBQTbROWqobU='

LINE_URL = 'https://notify-api.line.me/api/notify'
LINE_TOKEN = '48zl8RmuB0lZoPOoVmqowZzjsUE0P53JO7jfVFCyLwh'

FILE_URL = DIRECTORY + '/_data'
FILE_URL_BACK = DIRECTORY + '/_back_5m/'
FILE_URL_BACKTEST = DIRECTORY + '/BacktestResult/'
FILE_URL_QUANT_TOTAL = FILE_URL + '/QuantData.xlsx'
FILE_URL_DATA_5M = FILE_URL + '/BotData_5m.xlsx'
FILE_URL_DATA_BACK_5M = FILE_URL + '/BotData_5m_backup.xlsx'
FILE_URL_QUANT_LIST_5M = FILE_URL + '/QuantDataList_5m.pickle'
FILE_URL_QUANT_RANK_5M = FILE_URL + '/QuantDataRank_5m.xlsx'
FILE_URL_QUANT_LAST_5M = FILE_URL + '/QuantLast_5m.pickle'
FILE_URL_BALANCE_LIST_5M = FILE_URL + '/BalanceList_5m.pickle'
FILE_URL_BALANCE_LIST_TEST_5M = FILE_URL_BACKTEST + '/BalanceListTest_5m.pickle'